/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Accueil;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
//import outils.SingletonJDBC;
import outils.SingletonJDBC;
import java.sql.ResultSet;
import java.util.logging.Level;
import jeu.FenetreDeJeu;



/**
 *
 * @author abenelha
 */
public class AccueilLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccueilLogin.class.getName());

    /**
     * Creates new form AccueilLogin
     */
    public AccueilLogin() {
        String couleur = "";
        initComponents();
        jComboBox3.removeAllItems();  // vide les "Item 1, Item 2..."
        
        try {
            Connection connexion = SingletonJDBC.getInstance().getConnection();

            PreparedStatement requete = connexion.prepareStatement("SELECT couleur FROM abeille");
            ResultSet resultat = requete.executeQuery();
            while (resultat.next()) {
                
                couleur = couleur + " " + resultat.getString("couleur");
                
            }

            requete.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        if(!couleur.contains("blue")){
            jComboBox3.addItem("bleu");

        }
        if(!couleur.contains("vert")){
            jComboBox3.addItem("vert");

        }if(!couleur.contains("mauve")){
            jComboBox3.addItem("mauve");

        }if(!couleur.contains("rouge")){
            jComboBox3.addItem("rouge");

        }
//        jComboBox3.addItem("Vert");
//        jComboBox3.addItem("Mauve");
//        jComboBox3.addItem("Rouge");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        texteAccueil = new javax.swing.JLabel();
        texteConnectez = new javax.swing.JLabel();
        textePseudo = new javax.swing.JLabel();
        texteMDP = new javax.swing.JLabel();
        champPseudo = new javax.swing.JTextField();
        champMDP = new javax.swing.JTextField();
        boutonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        texteAccueil.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        texteAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texteAccueil.setText("Bonjour");

        texteConnectez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texteConnectez.setText("Connectez-vous à l'application ...");

        textePseudo.setText("Pseudo");

        texteMDP.setText("Mot de passe");

        boutonOK.setText("Entrez ...");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texteConnectez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textePseudo)
                            .addComponent(texteMDP))
                        .addGap(34, 34, 34)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(champMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(champPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonOK))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(texteAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texteAccueil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texteConnectez)
                .addGap(30, 30, 30)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textePseudo)
                    .addComponent(champPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texteMDP)
                    .addComponent(champMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(boutonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bonjour");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 29, 82, 28));

        jLabel2.setText("Connectez-vous à l'application ...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 236, -1));

        jLabel3.setText("Pseudo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        jLabel4.setText("Mot de passe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, -1, -1));

        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, -1));

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 172, 203, 30));

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 221, 73, -1));

        jButton1.setText("Sign up ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("Z:\\Desktop\\abeille mauve 4 .png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 70));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("comboCouleur"); // NOI18N
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setName("comboCouleur"); // NOI18N
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mauve", "Blue ", "Rouge", "Vert", "Jaune" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
                Connection connexion = SingletonJDBC.getInstance().getConnection();

                String pseudo = jTextPane1.getText();
                String mdp = new String(jPasswordField1.getPassword());

                String sql = "SELECT * FROM utilisateurs WHERE pseudo=? AND motdepasse=MD5(?)";
                PreparedStatement st = connexion.prepareStatement(sql);
                st.setString(1, pseudo);
                st.setString(2, mdp);

                ResultSet res = st.executeQuery();

                if (res.next()) {
                    jLabel2.setText("Connexion réussie !");
                    String name = res.getString("pseudo");
                    FenetreDeJeu fenetre = new FenetreDeJeu(name);
                    fenetre.setVisible(true);
                } else {
                    jLabel2.setText("Identifiants incorrects");
                }
                

                st.close();
                
//                Salon salon = new Salon();
//                this.setVisible(false);
//                salon.setVisible(true);
//                String sqlUpdate = "UPDATE abeille SET connecte=1 WHERE pseudo=?";
//                st.setString(1, pseudo); // pseudo du joueur courant
//                st.executeUpdate();
//                st.close();


         } catch (SQLException ex) {
                jLabel2.setText("Erreur SQL : " + ex.getMessage());
            } catch (IOException ex) {
            logger.log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try {
                    Connection connexion = SingletonJDBC.getInstance().getConnection();

                    String pseudo = jTextPane1.getText();
                    String mdp = new String(jPasswordField1.getPassword());

                    // 1) Vérifier si le pseudo existe déjà
                    String check = "SELECT * FROM utilisateurs WHERE pseudo=?";
                    PreparedStatement stCheck = connexion.prepareStatement(check);
                    stCheck.setString(1, pseudo);
                    ResultSet res = stCheck.executeQuery();

                    if (res.next()) {
                        jLabel2.setText("Pseudo déjà utilisé !");
                        stCheck.close();
                        return;
                    }
                    stCheck.close();

                    // 2) Insérer un nouveau compte dans utilisateurs
                    String sql = "INSERT INTO utilisateurs(pseudo, motdepasse) VALUES (?, MD5(?))";
                    PreparedStatement st = connexion.prepareStatement(sql);
                    st.setString(1, pseudo);
                    st.setString(2, mdp);
                    st.executeUpdate();
                    st.close();

                    // 3) Créer automatiquement une abeille pour ce joueur avec la couleur choisie
                    String couleurChoisie = jComboBox3.getSelectedItem().toString(); // <-- couleur de la JComboBox
                    String sqlAbeille = "INSERT INTO abeille (pseudo, x, y, pv, qnt_nectar, qnt_pollen, couleur , connecte) VALUES (?, ?, ?, ?, ?, ?, ? , ?)";
                    PreparedStatement stA = connexion.prepareStatement(sqlAbeille);

                    stA.setString(1, pseudo);        // même pseudo que l’utilisateur
                    stA.setInt(2, 0);                // x
                    stA.setInt(3, 0);                // y
                    stA.setInt(4, 20);               // pv
                    stA.setInt(5, 0);                // qnt_nectar
                    stA.setInt(6, 0);                // qnt_pollen
                    stA.setString(7, couleurChoisie); // <-- couleur choisie
                    stA.setInt(8, 0);
                    
                    stA.executeUpdate();
                    stA.close();

                    jLabel2.setText("Compte créé + Abeille " + couleurChoisie + " créée !");
                    Salon salon = new Salon();
                    this.setVisible(false);
                    salon.setVisible(true);

            } catch (SQLException ex) {
                jLabel2.setText("Erreur SQL : " + ex.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(() -> new AccueilLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonOK;
    private javax.swing.JTextField champMDP;
    private javax.swing.JTextField champPseudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel texteAccueil;
    private javax.swing.JLabel texteConnectez;
    private javax.swing.JLabel texteMDP;
    private javax.swing.JLabel textePseudo;
    // End of variables declaration//GEN-END:variables
}
