/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Accueil;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
//import outils.SingletonJDBC;
import outils.SingletonJDBC;
import java.sql.ResultSet;



/**
 *
 * @author abenelha
 */
public class AccueilLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccueilLogin.class.getName());

    /**
     * Creates new form AccueilLogin
     */
    public AccueilLogin() {
        String couleur = "";
        initComponents();
        setLocationRelativeTo(null);
        jComboBox3.removeAllItems();  // vide les "Item 1, Item 2..."
        
       
//  Couleurs autorisées (tout en français, sans espaces)
String[] toutes = {"bleu", "vert", "mauve", "rouge"};

//  Lire les couleurs déjà utilisées dans la table abeille
java.util.HashSet<String> prises = new java.util.HashSet<>();

try {
                    Connection connexion = SingletonJDBC.getInstance().getConnection();
                    PreparedStatement req = connexion.prepareStatement("SELECT couleur FROM abeille");
                    ResultSet rs = req.executeQuery();

                    while (rs.next()) {
                        String c = rs.getString("couleur");
                        if (c != null) {
                            prises.add(c.trim().toLowerCase()); // ✅ normaliser
                        }
                    }
                    rs.close();
                    req.close();

                } catch (SQLException ex) {
                    ex.printStackTrace();
                }

                // Ajouter seulement les couleurs libres
                for (String c : toutes) {
                    if (!prises.contains(c)) {
                        jComboBox3.addItem(c);
                    }
                }
       
//        if(!couleur.contains("blue")){
//            jComboBox3.addItem("bleu");
//
//        }
//        if(!couleur.contains("vert")){
//            jComboBox3.addItem("vert");
//
//        }if(!couleur.contains("mauve")){
//            jComboBox3.addItem("mauve");
//
//        }if(!couleur.contains("rouge")){
//            jComboBox3.addItem("rouge");
//
//        }
//        jComboBox3.addItem("Vert");
//        jComboBox3.addItem("Mauve");
//        jComboBox3.addItem("Rouge");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        texteAccueil = new javax.swing.JLabel();
        texteConnectez = new javax.swing.JLabel();
        textePseudo = new javax.swing.JLabel();
        texteMDP = new javax.swing.JLabel();
        champPseudo = new javax.swing.JTextField();
        champMDP = new javax.swing.JTextField();
        boutonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        texteAccueil.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        texteAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texteAccueil.setText("Bonjour");

        texteConnectez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texteConnectez.setText("Connectez-vous à l'application ...");

        textePseudo.setText("Pseudo");

        texteMDP.setText("Mot de passe");

        boutonOK.setText("Entrez ...");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texteConnectez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textePseudo)
                            .addComponent(texteMDP))
                        .addGap(34, 34, 34)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(champMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(champPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonOK))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(texteAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texteAccueil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texteConnectez)
                .addGap(30, 30, 30)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textePseudo)
                    .addComponent(champPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texteMDP)
                    .addComponent(champMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(boutonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(907, 913));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setText("Bonjour dans Beez-Run");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 510, 40));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel2.setText("Connectez-vous à l'application ...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 360, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel3.setText("Pseudo ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 80, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel4.setText("Mot de passe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        jTextPane1.setText("abeille");
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 150, 30));

        jPasswordField1.setText("123456");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 203, 30));

        jButton3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 100, 30));

        jButton1.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jButton1.setText("Sign up ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 100, 30));

        jComboBox3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mauve", "Blue ", "Rouge", "Vert", "Jaune" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-acceuil.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setPreferredSize(new java.awt.Dimension(671, 550));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 940, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
                     Connection connexion = SingletonJDBC.getInstance().getConnection();

                    String pseudo = jTextPane1.getText().trim();
                    String mdp = new String(jPasswordField1.getPassword());

                    if (pseudo.isEmpty() || mdp.isEmpty()) {
                        jLabel2.setText("Pseudo et mot de passe obligatoires");
                        return;
                    }

                    String sql = "SELECT * FROM utilisateurs WHERE pseudo=? AND motdepasse=MD5(?)";
                    PreparedStatement st = connexion.prepareStatement(sql);
                    st.setString(1, pseudo);
                    st.setString(2, mdp);

                    ResultSet res = st.executeQuery();

                    if (res.next()) {
                        jLabel2.setText("Connexion réussie !");

                        // ✅ UPDATE connecte = 1 avec un nouveau statement
                        String sqlUpdate = "UPDATE abeille SET connecte=1 WHERE pseudo=?";
                        PreparedStatement stUpdate = connexion.prepareStatement(sqlUpdate);
                        stUpdate.setString(1, pseudo);
                        stUpdate.executeUpdate();
                        stUpdate.close();

                        // ✅ Ouvrir le salon seulement si succès
                        Salon salon = new Salon(pseudo);
                        this.setVisible(false);
                        salon.setVisible(true);

                    } else {
                        jLabel2.setText("Identifiants incorrects");
                    }

                    res.close();
                    st.close();

                } catch (SQLException ex) {
                    jLabel2.setText("Erreur SQL : " + ex.getMessage());
                }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try {
                    Connection connexion = SingletonJDBC.getInstance().getConnection();

                    String pseudo = jTextPane1.getText().trim();
                    String mdp = new String(jPasswordField1.getPassword());

                    if (pseudo.isEmpty() || mdp.isEmpty()) {
                        jLabel2.setText("Pseudo et mot de passe obligatoires");
                        return;
                    }

                    // 1) Vérifier si le pseudo existe déjà
                    String check = "SELECT 1 FROM utilisateurs WHERE pseudo=?";
                    PreparedStatement stCheck = connexion.prepareStatement(check);
                    stCheck.setString(1, pseudo);
                    ResultSet res = stCheck.executeQuery();

                    if (res.next()) {
                        jLabel2.setText("Pseudo déjà utilisé !");
                        res.close();
                        stCheck.close();
                        return;
                    }
                    res.close();
                    stCheck.close();

                    // 2) Créer le compte
                    String sqlUser = "INSERT INTO utilisateurs(pseudo, motdepasse) VALUES (?, MD5(?))";
                    PreparedStatement stUser = connexion.prepareStatement(sqlUser);
                    stUser.setString(1, pseudo);
                    stUser.setString(2, mdp);
                    stUser.executeUpdate();
                    stUser.close();

                    // 3) Couleur choisie (on nettoie)
                    String couleurChoisie = jComboBox3.getSelectedItem().toString().trim().toLowerCase();
                    if (couleurChoisie.equals("blue")) couleurChoisie = "bleu";  // si tu veux stocker en français

                    // 4) Créer l'abeille + CONNECTE=1 
                    String sqlAbeille =
                        "INSERT INTO abeille (pseudo, x, y, pv, qnt_pollen, couleur, connecte) " +
                        "VALUES (?, ?, ?, ?, ?, ?, ?)";

                    PreparedStatement stA = connexion.prepareStatement(sqlAbeille);
                    stA.setString(1, pseudo);
                    stA.setInt(2, 0);
                    stA.setInt(3, 0);
                    stA.setInt(4, 5);
                    stA.setInt(5, 0);
                    stA.setString(6, couleurChoisie);
                    stA.setInt(7, 1); //  connecté dès l'inscription
                    stA.executeUpdate();
                    stA.close();

                    jLabel2.setText("Compte créé : " + pseudo + " (" + couleurChoisie + ")");

                    // ✅ ouvrir salon avec le pseudo
                    Salon salon = new Salon(pseudo);
                    this.setVisible(false);
                    salon.setVisible(true);

                } catch (SQLException ex) {
                    jLabel2.setText("Erreur SQL : " + ex.getMessage());
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(() -> new AccueilLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonOK;
    private javax.swing.JTextField champMDP;
    private javax.swing.JTextField champPseudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel texteAccueil;
    private javax.swing.JLabel texteConnectez;
    private javax.swing.JLabel texteMDP;
    private javax.swing.JLabel textePseudo;
    // End of variables declaration//GEN-END:variables
}
